### PR TITLE
Allow base 4.12, as released with GHC 8.6.

### PR DESCRIPTION
**Pull request by quasicomputational**
There's actually an old version of vector-binary-instances that the
solver is able to use on GHC 8.6, but I presume that the latest
version would be better to use if possible.

This also adds 8.6 to the Travis configuration.

### CODE REVIEW

**Comment by bgamari** [comment]
This seems to [break CI](https://travis-ci.org/bgamari/vector-binary-instances/jobs/435775328).

**Comment by quasicomputational** [comment]
@bgamari Can you trigger a build of master, please? 

I don't think that this PR is causing it; rather, at some point since the last Travis run, `criterion` has grown a necessary transitive dependency on `vector-binary-instances` and cabal-install doesn't like the apparent cycle.

At the component level this is actually feasible (i.e., not a cycle), and haskell/cabal#1575 is tracking that.

**Comment by quasicomputational** [comment]
Actually, thinking on it more, the bug *should* trigger on master, since it's also affecting the 7.10 and 8.0 builders. I'm not entirely sure why the solver isn't finding solutions that it previously could - maybe revisions?

**Comment by quasicomputational** [comment]
I've got it and it's alarmingly simple: the previous `.travis.yml` script doesn't build tests or benchmarks, but the new one does. I don't know how to get the regeneration script to do that; there is a `--no-no-tests-no-bench` but no corresponding `--no-tests-no-bench` flag? Uncommenting the commented out `env` line doesn't stick through regenerations, either.

**Comment by RyanGlScott** [comment]
Indeed, I don't believe such an option exists. That being said, I don't think we should let this issue be a blocker. For the time being, I think manually removing any uses of `--enable-benchmarks` would be the simplest solution.

In the long term, what we should look into is putting the benchmarks into a separate `.cabal` file (_à la_ [`primitive`](https://github.com/haskell/primitive/blob/0bc3b898bc22f04c3ed5ef83c1aa13cd98d461d7/bench/primitive-benchmarks.cabal)) and build the benchmarks as a separate component. This would avoid dependency cycles, since we could simply build `criterion` afresh each time based on the in-place version of `vector-binary-instances`. (If rebuilding many dependencies on each Travis build is a concern, we could alternatively switch over to using `gauge` instead, which does not depend on `vector-binary-instances`.)

**Comment by quasicomputational** [comment]
Sounds sensible. I've gone ahead and hand-edited `.travis.yml`.

**Comment by RyanGlScott** [comment]
I've opened #16 to get rid of the manual hacks we had to put in the generated `.travis.yml` file.

**Pull request merged**
