### PR TITLE
Bump base bound.

### PR DESCRIPTION
**Pull request by athas**

### CODE REVIEW

**Comment by juhp** [comment]
This is blocking various packages in Stackage Night (ghc-9.4).
It looks like a Hackage revision might be sufficient to take care of this for now?

**Comment by Mikolaj** [comment]
Could one of you bump the base again, for GHC 9.6? It's blocking at least https://github.com/haskellari/strict-containers/issues/12

**Comment by Mikolaj** [comment]
Actually, it seems @bgamari did it last time: https://hackage.haskell.org/package/vector-binary-instances

**Comment by athas** [comment]
I don't have commit access to this repository and this PR is long obsolete.

**Pull request closed without merging**
