### PR TITLE
Support GHC 9.0 by bumping bounds and switching to tasty-bench.

### LINKED ISSUE #21: Loosen bounds on base
This works with GHC 9.0.1

### PR DESCRIPTION
**Pull request by athas**
Fixes #21.

### CODE REVIEW

**Comment by athas** [comment]
Ping @bgamari, I think you are the most active person with commit access.

**Comment by athas** [comment]
Ping @bgamari again.  I don't know how to see who else has commit access.  I'm beginning to think GHC 9.2 might be out before vector-binary-instances even manages to support 9.0...

**Comment by bgamari** [comment]
Oh dear, sorry about that the latency, @athas!

**Comment by athas** [comment]
Thanks!

**Comment by bgamari** [comment]
Thanks for pinging me; it's very easy to lose track of these things.

**Pull request merged**
